spring.application.name=mercedes_shop
server.port=8080

spring.data.mongodb.uri=mongodb+srv://hoangthuhang070904_db_user:hoangthuhang070904_db_user@cluster0.xqh93qz.mongodb.net/?appName=Cluster0

spring.data.mongodb.database=mecshop

# Cloudinary configuration
cloudinary.cloud-name=dawxdwbjk
cloudinary.api-key=583579923368498
cloudinary.api-secret=kbkcq1G4JigsxcEc1i_Ifg-Omhk

# File upload configuration
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB

# Logging configuration - Turn OFF MongoDB logs completely
logging.level.org.springframework.data.mongodb.core.MongoTemplate=OFF
logging.level.org.mongodb.driver=OFF
logging.level.org.springframework.data.mongodb=OFF
logging.level.org.springframework.data=WARN
logging.level.org.example=INFO
logging.level.root=INFO

# VNPay Configuration (Sandbox for testing)
vnpay.tmn-code=XPD1OJP4
vnpay.hash-secret=NXV2O5B3V0QSA5VLMHH0D1HYH65P2WEN
vnpay.url=https://sandbox.vnpayment.vn/paymentv2/vpcpay.html
vnpay.return-url=http://localhost:5173/vnpay-return
vnpay.version=2.1.0
vnpay.command=pay
vnpay.order-type=other